backend/administrator/urls.py
from django.urls import path, re_path
from . import views

app_name = 'administrator'


urlpatterns  = [

    path('administrator/',views.adminhome , name = 'admin'),
    path('administrator/messages/',views.MessageListView.as_view() , name = 'messagelist'),
    re_path('administrator/messages/(?P<pk>[0-9]+)/', views.MessageDetailView.as_view() , name = 'messagedetail'),

]

backend/ufs/urls.py
from django.urls import path
from . import views

app_name = 'ufs'

urlpatterns =[
path('messages/',views.MessageCreateView.as_view(),name = 'ufs-messages'),
]

backend/administrator/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

backend/administrator/views.py
from django.shortcuts import render
from ufs.models import Message
from django.views.generic import DetailView, ListView , CreateView , DeleteView , TemplateView

class MessageListView(ListView):
    model = Message
    template_name = 'administrator/complaints.html'
    context_object_name = 'messages'

    def get_queryset(self):
        return Message.objects.all()

class MessageDetailView(DetailView):
    model = Message
    template_name = 'administrator/complaint_description.html'
    context_object_name = 'complaint_detail'

def adminhome(request):
    return render(request,'administrator/admin.html')

backend/administrator/templates/administrator/admin.html
{% extends 'core/base.html' %}
{% block content %}


<style>
	.custom-div{
		margin:  0 4%;
	}
</style>
<div class="container">
	<div class="row col-xs-12">
		<ul>
		  	<div class="well col-xs-3 custom-div custom-box-shadow">
		  		<img src="../../../media/email.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block">
		  		<li class="well list-group-item-info thumbnail"><a class="" href="/administrator/messages">Show Inbox -- UFS</a></li>
		  	</div>
		  	<div class="well col-xs-3 custom-div custom-box-shadow">
		  	<img src="../../../media/auction.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block">
		  		<li class="well list-group-item-info thumbnail"><a href="/shop/all_auctions/">List all Auctions and bidding</a></li>
		  	</div>

		  	<div class="well col-xs-3 custom-div custom-box-shadow">
		  	<img src="../../../media/notebook.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block">
		  		<li class=" well list-group-item-info thumbnail"><a href="/shop/all_services/">List all services</a></li>
		  	</div>
		</ul>
	</div>
</div>

{% endblock %}

backend/administrator/templates/administrator/complaint_description.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="jumbotron">
			<ol class="well jumbotron list-group-item-info">
			  <b>
				  <li class="">Name :  {{complaint_detail.title}} </li>
				  <li>Effected Crop :  {{complaint_detail.effected_crop}} </li>
				  <li>Description :  {{complaint_detail.Description}} </li>
				  <img src="{{complaint_detail.Images}}" alt="">
			  </b>
			</ol>
		</div>
	</div>
</div>
{% endblock %}

backend/administrator/templates/administrator/complaints.html
{% extends 'core/base.html' %}

{% block content %}





<style>
	.custom-rule{
		display: table;
		margin:  0 auto;
		width:  55%;
	}
	h2{
	  color:  #337ab7;
	  text-align: center;
	  box-shadow: 2px 2px 2px 1px rgba(0,0,0,0.2) !important;
	}
</style>

<div class="list-group custom-rule">
	<!-- <div class="container"> -->
		<div class="row">
			<h2 class="thumbnail well">Complaints List</h2>
		</div>
		<div class="row">
			<div class="well col-md-12" style="box-shadow: 2px 2px 2px 1px rgba(0,0,0,0.2) !important">
				<ol>
					{% for message in messages %}
					  <div class="btn btn-info well thumbnail" style="background: #5bc0de"> <li ><a class="well btn-primary list-group-item list-group-item-info" href="{% url 'administrator:messagedetail' message.pk %}">{{message.effected_crop }}  -- {{message.title}}  --  {{message.timestamp | timesince }} ago</a></li></div>
					{% endfor %}
				</ol>
			</div>
		</div>
	<!-- </div> -->
</div>








{% endblock %}