backend/customercorner/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views as customercorner

app_name = 'customercorner'

urlpatterns = [

    path('all_products/' , customercorner.AllProductList.as_view() , name ='products' ),
    re_path('product_details/(?P<pk>[0-9]+)/' , customercorner.ProductDetailView.as_view() , name ='product_detail' ),
    path('create_product/',customercorner.ProductCreateView.as_view(),name='create_product'),
    path('categories/',customercorner.Categories.as_view(),name='categories'),
    re_path('categories/(?P<pk>[0-9]+)/',customercorner.category_products_list ,name='category_products')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

backend/ufs/urls.py
from django.urls import path
from . import views

app_name = 'ufs'

urlpatterns =[
path('messages/',views.MessageCreateView.as_view(),name = 'ufs-messages'),
]

backend/customercorner/models.py
from django.db import models

class Product_type(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=15,null=False,blank=False)
    image = models.ImageField()

    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    Product_name = models.CharField(max_length = 10, blank = False , null = False)
    Product_type = models.ForeignKey(Product_type,on_delete=models.CASCADE)
    Product_version = models.CharField(max_length = 15, blank = False , null = False)
    Product_Images = models.ImageField()


    def __str__(self):
        return self.Product_name + ' -- ' + self.Product_version

    @property
    def Product_typ(self):
        return str(self.Product_type).capitalize()

    @property
    def version(self):
        return self.Product_version

    def productwithversion(self):
        return str(self.Product_version) +" " + str(self.Product_name)


    ''' This method can be called in the template to get the value related in the other table'''
    def preproductinfo(self):
        return PreProductInfo.objects.filter(Select_Product=self)

    def NutrionalContent(self):
        return NutrionalContent.objects.filter(Select_Product = self)


    def GoodQualityCondition(self):
        return GoodQualityCondition.objects.filter(Select_Product = self)

    def BadQualityCondition(self):
        return BaddQualityCondition.objects.filter(Select_Product = self)

    def all_productinfo(self):
        return self.pk.PreProductInfo_set.all()

    def all_pre_productinfo(self):
        return self.PreProductInfo_set.all()

    def get_image(self):
        self.Product_Images.url


class PreProductInfo(models.Model):
    id = models.AutoField(primary_key=True)
    Seasons_list = (
    ('Summer','Summer'),
    ('Winter','Winter')
    )
    Soil_Choices = (
    ('alluvial','Alluvial'),
    ('loamy','Loamy')
    )
    Select_Product = models.ForeignKey(Product,on_delete=models.CASCADE,default = None)
    Season = models.CharField(max_length = 10 , choices = Seasons_list,default=None)
    Soil_type = models.CharField(max_length = 10 , choices = Soil_Choices,default = None)
    Investment_cost = models.IntegerField(blank = False,null=False)



    def __str__(self):
        return self.Select_Product.Product_name + ' -- '+ str(self.Season).capitalize() + '--' + str(self.Soil_type).capitalize()

    @property
    def cost(self):
        return str(self.Investment_cost) + ' RS/-'

    @property
    def soil(self):
        return str(self.Soil_type).capitalize()

class NutrionalContent(models.Model):
    id = models.AutoField(primary_key=True)
    Select_Product = models.ForeignKey(Product,on_delete=models.CASCADE,default = None)
    # NutrionalData = models.TextField(max_length=1500,help_text='Please seprate the Nutrional Content by comma\'s',null=False,blank=False)
    ConsumptionEffect = models.TextField(max_length=1500,help_text='Please seprate the Consumption Effect by comma\'s',null=False,blank=False)

    NutrionChart = models.ImageField()

    Fat = models.IntegerField()
    Carbohydrates = models.IntegerField()
    Protein = models.IntegerField()
    Sugar = models.IntegerField()

    def __str__(self):
        return "Nutrional content -- " + str(self.Select_Product.Product_version) + " " + str(self.Select_Product.Product_name)

class GoodQualityCondition(models.Model):
    id = models.AutoField(primary_key=True)
    Select_Product = models.ForeignKey(Product,on_delete=models.CASCADE,default = None)
    CheckingConditions = models.TextField(max_length=1500,help_text='Please seprate the Good Conditions of the Product by comma\'s',null=False,blank=False)
    Good_Images = models.ImageField()

class BadQualityCondition(models.Model):
    id = models.AutoField(primary_key=True)
    Select_Product = models.ForeignKey(Product,on_delete=models.CASCADE,default = None)
    CheckingConditions = models.TextField(max_length=1500,help_text='Please seprate the Good Conditions of the Product by comma\'s',null=False,blank=False)
    Good_Images = models.ImageField()


class CultivationMethods(models.Model):
    id = models.AutoField(primary_key=True)
    Seasons_list = (
    ('Summer','Summer'),
    ('Winter','Winter')
    )
    Soil_Choices = (
    ('alluvial','Alluvial'),
    ('loamy','Loamy')
    )
    Select_Product = models.ForeignKey(Product,on_delete=models.CASCADE)
    Description = models.CharField(max_length = 1500)
    Investment_cost = models.IntegerField()
    Season = models.CharField(max_length = 10 , choices = Seasons_list,default=None)
    Soil_type = models.CharField(max_length = 10 , choices = Soil_Choices,default = None)

backend/customercorner/forms.py
from . models import Product
from django import forms

class ProductCreateForm(forms.ModelForm):
    
    class Meta:
        Product

backend/customercorner/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView , CreateView , DeleteView , TemplateView

from .models import Product, Product_type


class AllProductList(ListView):
    model = Product
    template_name = 'customercorner/all_products.html'
    context_object_name = 'all_products'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'customercorner/product_detail.html'
    context_object_name = 'product' #will provide the class object with data and can be accessed with the help of the dot operator

class ProductCreateView(CreateView):
    model = Product
    template_name = 'customercorner/create_product.html'
    success_url = '/all_products/'
    context_object_name = 'form'
    fields = '__all__'


class Categories(ListView):
    model = Product_type
    template_name = 'customercorner/categories.html'
    context_object_name = 'categories'

def category_products_list(request,pk):
    data = Product_type.objects.get(id=pk)
    context = {'all_products' : data}
    return (request,'customercorner/category_products.html',context)

backend/customercorner/templates/customercorner/all_products.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>List of all Products</title>
  </head>
  <body><ul>
    {% for product in all_products %}
    <li><a href="{% url 'customercorner:product_detail' product.id %}">{{product}}</a> {{product.Product_typ}}</li>
    {% endfor %}
  </ul>
  </body>
</html>

backend/customercorner/templates/customercorner/categories.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>All Product Categories</title>
  </head>
  <body>
      {% for category in categories %}
        {{ category.name }}
        <img src="{{category.image.url }}" alt="{{category.name}}">
      {% endfor %}
  </body>
</html>

backend/customercorner/templates/customercorner/category_products.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>

backend/customercorner/templates/customercorner/create_product.html
{% extends 'core/base.html'%}

{% block content %}
 {% load bootstrap3 %}
  {% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}
  
<style>

.custom-row{
	display: table;
	margin:  0 auto;
	/*width:  500px;*/
}
.container{
}
</style>
  <body>
    <div class="container">
    	<div class="row">
    		<div class="custom-row">
    			<div class="well col-xs-12 col-md-12 col-lg-12">
    				<div class="col-sm-10 col-md-12 ">
    						<h1>Create a new Product</h1>
    						<form method="post" class="form"> {% csrf_token %}
    						{% bootstrap_form form %}
    						  <!-- {{form.as_p}} -->
    						  {% buttons %}
    						      <button type="submit" name="button" class="btn btn-primary">
    						        {% bootstrap_icon "star" %} Create new product
    						      </button>
    						    {% endbuttons %}
    						  <!-- <button type="submit" name="button" class="btn btn-primary">Create new Product</button> -->
    						</form>
    				</div>	
    			</div>
    		</div>
    	</div>
    </div>
  </body>

  {% endblock %}

backend/customercorner/templates/customercorner/product_detail.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width ,maximum-scale=1.0 ">
    <title>Details | {{product.Product_version}} |{{product.Product_name}}</title>
    <link rel="stylesheet" href="{% static "customercorner/css/main.css" %}">
  </head>
  <body>

          <div class = 'main'>
            <ul>

          <h1>General Details : </h1>
          <li>Name : {{product.Product_name}}</li>
          <li>Version : {{product.Product_version}}</li>
          <li>Product Category : {{product.Product_typ}}</li>
          <img src="{{product.get_image}}" alt="{{product.Product_name}}">
          <img src="{{ product.Product_Images.url }}" alt="" >



        </ul>
        </div>
<div>
</div>
        <div >

          <h1>Pre Product info :</h1>

          {% for info in product.preproductinfo %}
          <p> <b>Method {{forloop.counter}} </b></p>
          <li> Preffered Season : {{ info.Season }} </li>
          <li> Investment Cost : {{ info.cost }} </li>
          <li> Preffered Soil : {{ info.soil }} </li>

            {% endfor %}


        </div>

        <div>

          <h1>Nutrional Content and Advantages of {{product.productwithversion}}:</h1>
          {% for nutrients in product.NutrionalContent %}
          <li><p><b>Nutrional Content</p></b></li>
          {{nutrients.NutrionalData}}
          <br>
          <p>Consumption Effects</p>
          {{nutrients.ConsumptionEffect}}
          {% endfor %}

        </div>

  </body>
</html>