backend/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views as core_views

app_name = 'core'

urlpatterns = [
    path('', core_views.home, name='home'),
    path('login', core_views.login_user,name='login'),

    path('log_in/', auth_views.LoginView.as_view(template_name='core/login.html'),name='login'),
    path('logout', core_views.my_logout_then_login, name='logout'),
    
    path('signup', core_views.signup, name='signup'),
]

backend/shop/urls.py
from django.urls import path, re_path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


app_name = 'shop'

urlpatterns = [

    path('shop/',login_required(TemplateView.as_view(template_name = 'shop/shop.html')) , name = 'shop'),
    path('shop/all_auctions/',views.AllAuctions.as_view() , name = 'all_auctions'),
    path('shop/auction/', views.AuctionCreateView.as_view(template_name = 'shop/auction.html') , name = 'created_auction'),
    path('shop/myauction/', views.MyAuctions.as_view(), name = 'myauctions'),
    re_path('shop/myauction/(?P<pk>[0-9]+)/', views.AuctionDetailView.as_view(), name = 'auction_detail'),
    # path('auction/')
    path('shop/services/',views.ServiceCreateView.as_view(), name = 'service'),
    path('shop/all_services/',views.ServiceListView.as_view(), name = 'all_services'),
    re_path('shop/service/(?P<pk>[0-9]+)/',views.ServiceDetailView.as_view(), name = 'service_detail'),
    path('shop/biddinglist/',views.BiddingList.as_view(),name = 'biddinglist'),
    re_path('shop/bidding/(?P<pk>[0-9]+)/',views.BiddingCreateView.as_view(),name = 'bidding')
]

backend/ufs/urls.py
from django.urls import path
from . import views

app_name = 'ufs'

urlpatterns =[
path('messages/',views.MessageCreateView.as_view(),name = 'ufs-messages'),
]

backend/shop/models.py
from django.db import models
from customercorner.models import Product
from django.contrib.auth.models import User


class Auction(models.Model):
    id = models.AutoField(primary_key=True)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    Product = models.ForeignKey(Product,on_delete=models.CASCADE)
    Price = models.IntegerField()
    Quality = models.CharField(max_length = 150)
    image = models.CharField(max_length = 500)
    Description = models.CharField(max_length = 150)
    Min_order = models.PositiveIntegerField()
    Address = models.CharField(max_length = 200)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return str(self.Product) + str(self.Price)

    def all_bidding(self):
        return self.bidding_set.all()

class Bidding(models.Model):
    id = models.AutoField(primary_key=True)
    Auction = models.ForeignKey(Auction,on_delete=models.CASCADE)
    bid_by = models.ForeignKey(User,on_delete=models.CASCADE)
    Bidding_Price = models.IntegerField()
    sample = models.BooleanField()
    Query = models.CharField(max_length = 150)

    def __str__(self):
        return str(self.Auction)

    def userwithprice(self):
        return str(self.bid_by) + ' bid ' + str(self.Bidding_Price) + 'Rs/- on your product'


class Services(models.Model):
    id = models.AutoField(primary_key=True)
    Company_Name = models.CharField(max_length = 150)
    Service_name = models.CharField(max_length = 200)
    Price = models.IntegerField()
    Product = models.ManyToManyField(Product)
    Description = models.CharField(max_length = 150)
    timestamp = models.DateTimeField(auto_now_add=True)
    images = models.CharField(max_length = 500)

    def __str__(self):
        return self.Company_Name

backend/shop/forms.py
from django import forms
from shop.models import Services
from customercorner.models import Product

class ServiceCreateForm(forms.ModelForm):
    Product = forms.ModelMultipleChoiceField(
            widget=forms.CheckboxSelectMultiple, queryset = Product.objects.all()
            )
    class Meta:
        model  = Services
        fields = ['Company_Name' ,'Service_name' ,'Price', 'Product','Description','images']

backend/shop/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView , ListView
from .models import Auction , Services , Bidding
from .forms import ServiceCreateForm

class AuctionCreateView(LoginRequiredMixin,CreateView):
    model = Auction
    fields = ['Product','Price','Quality','Description','Min_order','Address','image']
    context_object_name = 'form'
    success_url = '/shop/myauction'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        obj.save()
        return redirect('/shop/myauction')


class AllAuctions(ListView):
    model = Auction
    context_object_name = 'AllAuctions'
    template_name = 'shop/all_auctions.html'


class MyAuctions(ListView):
    template_name = 'shop/myauction.html'
    context_object_name = 'data'

    def get_queryset(self):
        data = Auction.objects.all().filter(created_by = self.request.user)
        return data

class AuctionDetailView(DetailView):
    model = Auction
    template_name = 'shop/auction_detail.html'
    context_object_name = 'Auction_Detail'

class ServiceCreateView(LoginRequiredMixin,CreateView):
    model = Services
    form_class = ServiceCreateForm
    template_name = 'shop/services.html'
    success_url = '/shop/services'

class ServiceListView(ListView):
    model = Services
    template_name = 'shop/all_services.html'
    context_object_name = 'All_services'

class ServiceDetailView(DetailView):
    model = Services
    template_name = 'shop/service_detail.html'
    context_object_name = 'service_detail'


class BiddingList(ListView):
    model = Auction
    context_object_name = 'AllAuctions'
    template_name = 'shop/all_bid_auction.html'


class BiddingCreateView(LoginRequiredMixin,CreateView):
    model = Bidding
    fields = ['Bidding_Price','sample','Query']
    template_name = 'shop/bidding.html'
    context_object_name = 'data'

    def get_context_data(self,**kwargs):
        context = super(BiddingCreateView,self).get_context_data(**kwargs)
        context['data'] = Auction.objects.get(pk = self.kwargs['pk'])
        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.bid_by = self.request.user
        # print self.kwargs['pk']
        a = Auction.objects.get(pk = self.kwargs['pk'])
        obj.Auction = a
        obj.save()
        return redirect('/shop/myauction')

backend/shop/templates/shop/all_auctions.html
{% extends 'core/base.html' %}

{% block title %}{% endblock %}

{% block content %}








<style>
	.custom-rule{
		display: table;
		margin:  0 auto;
		width:  55%;
	}
	h2{
	  color:  #337ab7;
	  text-align: center;
	  box-shadow: 2px 2px 2px 1px rgba(0,0,0,0.2) !important;
	}
</style>

<div class="list-group custom-rule">
	<!-- <div class="container"> -->
		<div class="row">
			<h2 class="thumbnail well">All Auctions</h2>
		</div>
		<div class="row">
			<div class="well col-md-12" style="box-shadow: 2px 2px 2px 1px rgba(0,0,0,0.2) !important">
				<ol>
					{% for auction in AllAuctions %}
					  <div class="btn btn-info well thumbnail" style="background: #5bc0de"> <li ><a class="well btn-primary list-group-item list-group-item-info" href="{% url 'shop:auction_detail' auction.pk %}">{{auction}} -- {{auction.timestamp | timesince }} ago</a></li></div>
					{% endfor %}
				</ol>
			</div>
		</div>
	<!-- </div> -->
</div>






{% endblock %}

backend/shop/templates/shop/all_bid_auction.html
{% extends 'core/base.html' %}

{% block title %}All Auctions | Kisan Mill |{% endblock %}


{% block content %}
<style>
	.custom-rule{
		display: table;
		margin:  0 auto;
		width:  55%;
	}
	h2{
	  color:  #337ab7;
	  text-align: center;
	  box-shadow: 2px 2px 2px 1px rgba(0,0,0,0.2) !important;
	}
</style>

<div class="list-group custom-rule">
	<!-- <div class="container"> -->
		<div class="row">
			<h2 class="thumbnail well">List of All Auctions for the Bidding</h2>
		</div>
		<div class="row">
			<div class="well col-md-12" style="box-shadow: 2px 2px 2px 1px rgba(0,0,0,0.2) !important">
				<ol>
					{% for auction in AllAuctions %}
					  <div class="btn btn-info well thumbnail" style="background: #5bc0de"> <li ><a class="well btn-primary list-group-item list-group-item-info" href="{% url 'shop:bidding' auction.pk %}">{{auction}} -- {{auction.Price}} Rs/Kg -- {{auction.timestamp | timesince }} ago {{auction.created_by}} -- <code class="btn " style="border: 1px solid #c7254e">bid now</code></a></li></div> <br>
					{% endfor %}
				</ol>
			</div>
		</div>
	<!-- </div> -->
</div>


{% endblock %}

backend/shop/templates/shop/all_services.html
{% extends 'core/base.html' %}
{% block title %}All Services{% endblock %}
{% block content %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}


<style>
	.custom-rule
	{
		display: table;
		margin:  0 auto;
		width:  55%;
	}
	h1{
	  color:  #337ab7;
	  text-align: center;
	}
</style>
<div class="list-group custom-rule">
<h1 class="thumbnail well custom-box-shadow">Services for the Kisan</h1>

	<ol class="well col-md-12 custom-box-shadow">
		{% for service in All_services %}
		  	<div class="btn btn-info well thumbnail" style="background: #5bc0de"><li class=""><a class="well btn-primary list-group-item list-group-item-info" href="{% url 'shop:service_detail' service.pk %}">{{service}}</a></li></div>
		{% endfor %}
	</ol>
</div>
{% endblock %}

backend/shop/templates/shop/auction.html
{% extends 'core/base.html' %}

{% block content %}
{% load bootstrap3 %}
  {% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}
  <!-- <h2>Log in to My Site</h2> -->
<style>
  .custom-row{
    display: table;
    margin:  0 auto;
    width:  700px;
  }
h1{
  color:  #337ab7;
  text-align: center;
}
 hr{
    height:  1px;
    background: #337ab7;
    opacity:  0.2;
  }
  .back-img{
    /*background: url('/media/stonehaven.png') no-repeat center center fixed;*/
    background-size: cover;
   }
</style>
  <body>

    <div class="container">
      <div class="row col-xs-12 col-sm-12 col-md-12">
        <div class="custom-row">
          <div class="well col-xs-12 col-md-12 col-lg-12 custom-box-shadow back-img">
            <div class="col-sm-10 col-md-12 ">
                <h1>Create New Auction</h1>
                <hr>
                <form method="post" class="form"> {% csrf_token %}
                  <input type="hidden" name="next" value="{{ next }}" />
                {% bootstrap_form form %}
                  <!-- {{form.as_p}} -->
                  <br>
                  {% buttons %}
                      <button type="submit" name="button" class="btn btn-primary col-sm-12">
                        {% bootstrap_icon "star" %} Create Auction
                      </button>
                    {% endbuttons %}
                  <!-- <button type="submit" name="button" class="btn btn-primary">Create new Product</button> -->
                </form>
            </div>  
          </div>
        </div>
      </div>
    </div>

    <!-- <h1>Auction</h1>
    <div class="main">

    <form method="post"> {% csrf_token %}
      {{form.as_p}}

      <button type="submit" name="button">Create Auction</button>
    </form>
  </div> -->
  </body>
{% endblock %}

backend/shop/templates/shop/auction_detail.html
			{% extends 'core/base.html' %}

			{% block title %}Auction Detail {% endblock %}

			{% block content %}
			{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}

<style>
	.custom-jumbotron{
		border:  1px solid #e0e0e0;
		box-shadow: 2px 3px 9px -1px rgba(0,0,0,0.3);
	}
	h2{
		font-weight:  bold;
		font-size:  2em;
		font-family:  'Raleway';
	}
</style>




<div class="container">
	<div class="row">
		<div class="jumbotron custom-jumbotron">
			<h2 class="display-3 ">Details of Auction:</h2>
			<ul class=" lead">
			<li> Product name : {{Auction_Detail.Product}} </li>
			<li>Price : <code>{{Auction_Detail.Price}} Rs/Kg </code></li>
			<li>Min_order : <code>{{Auction_Detail.Min_order}}</code></li>
			<li>Quality : {{Auction_Detail.Quality}}</li>
			<img src="{{Auction_detail.image}}" alt="">
			<li>Created at : <code>{{ Auction_Detail.timestamp | timesince }} ago</code></li>
			</ul>
			<hr class="my-4">

			<h2>Biddings:</h2>
			{% if Auction_Detail.all_bidding %}
				<li><p>All bidding to this Auction</p> </li>
					{% for bid in Auction_Detail.all_bidding %}
				<ul>
					<li>{{bid.userwithprice}}</li>
				</ul>

				{% endfor %}

			{% else %}
				<ul>
				<code><li class="lead"><p>There is no bidding for this Auction</p> </li></code>
				</ul>
			{% endif %}
		</div>
	</div>
</div>
			

{% endblock %}

backend/shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Kisan Shop | Kisan Mill | Kisan Mill | Agriculture | Rural Development Hackathon 2018 {% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>Kisan Mill</h1>
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

backend/shop/templates/shop/bidding.html
{% extends 'core/base.html' %}

{% block title %}Bidding | {{block.super}}{% endblock %}
{% block content %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}
  <!-- <h2>Log in to My Site</h2> -->
<style>
  .custom-row{
    display: table;
    margin:  0 auto;
    width:  700px;
  }
   h1{
     color:  #337ab7;
     text-align: center;
   }
  hr{
     height:  1px;
     background: #337ab7;
     opacity:  0.2;
   }
   label[for=id_sample]{
   	font-weight: bold !important;		
   	vertical-align: bottom;
   }
</style>
  <div class="container">
    <div class="row col-xs-12 col-sm-12 col-md-12">
      <div class="custom-row well custom-box-shadow">
      <h1>Welcome to the Bidding Shop</h1>
      <hr>
      	<div class="left col-xs-5 well " >
      		<p class="well" style="background: #337ab7; color: #fff; font-family: 'Raleway'">Product Details : </p>
      		<div class="" style="font-family: 'Raleway'"><b>Product : {{data.Product}}</b>
      		<br><b>Price : <code>{{data.Price}} Rs/Kg</code></b></div>
      	</div>
        <div class=" col-xs-7 col-md-7 col-lg-7 ">
          <div class="col-sm-10 col-md-12 ">
              <!-- <h1>Welcome to the bidding shop</h1> -->
              <!-- <hr> -->
              <form method="post" class="form"> {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
              {% bootstrap_form form %}
                <!-- {{form.as_p}} -->
                <br>
                {% buttons %}
                    <button type="submit" name="button" class="btn btn-primary col-xs-12">
                      {% bootstrap_icon "star" %} Place bid
                    </button>
                  {% endbuttons %}
                <!-- <button type="submit" name="button" class="btn btn-primary">Create new Product</button> -->
              </form>
          </div>  
        </div>
      </div>
    </div>
  </div>
{% endblock %}

backend/shop/templates/shop/myauction.html
{% extends 'core/base.html' %}
{% block content %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}
<style>
	.custom-rule{
		display: table;
		margin:  0 auto;
		width:  55%;
	}
	h1{
	  color:  #337ab7;
	  text-align: center;
	}
</style>
<ul>
 <li class="btn  well list-group-item-info"><a href="/shop">{% bootstrap_icon "star" %}Back to Kisan shop</a></li>
  <!-- <li><a href="/shop/auction/">Create an Auction</a></li>
  <li><a href="/shop/myauction/">My Auctions List</a></li> -->
</ul>


<ol>


<div class="list-group custom-rule">
<h1 class="well thumbnail custom-box-shadow">My Auctions and Biddings<br>
<!-- <h1 class="thumbnail well"> -->Services for the Kisan</h1>

	<ol class="well col-md-12 custom-box-shadow">
		{% for datum in data %}
		  	<div class="btn btn-info well thumbnail" style="background: #5bc0de"><li class=""><a class="well btn-primary list-group-item list-group-item-info" href="{% url 'shop:auction_detail' datum.pk %}">({{datum}}) --- {{datum.Price}} Rs/Kg </a></li></div>
		{% endfor %}
	</ol>
</div>



<!-- {% for datum in data %} -->
<!-- <ul>

 {% for data in datum.bidding_set.all %}
 <li>{{data.userwithprice}} </li>
 {% endfor %}
</ul> -->
<!-- {% endfor %} -->
</ol>


{% endblock %}

backend/shop/templates/shop/service_detail.html
{% extends 'core/base.html' %}

{% block title %}Welcome to {{service_detail.Company_Name}} Group {% endblock %}

{% block content %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}

<style>
	.custom-jumbotron{
		border:  1px solid #e0e0e0;
		box-shadow: 2px 3px 9px -1px rgba(0,0,0,0.3);
	}
</style>

<div class="container ">
	<div class="row">
		<div class="jumbotron custom-jumbotron">
			<h2 class="display-3">Details of {{ service_detail.Company_Name }} :</h2>
			<hr class="my-4">
			<ul class="lead list-group">
			  <li class=""><p>Service Name : {{ service_detail.Service_name}}</p> </li>
			  <li><p>Service Price : <code>{{ service_detail.Price}}</code></p> </li>
			  <li class="">
			  	<p>Supported Product : </p>
				  	<ol>
			  			{% for pro in service_detail.Product.all %}
				  		<li>{{pro}}</li>
			  			{% endfor %}
			  		</ol>
			  </li><br>
			<li>Description : {{service_detail.Description}}</li>
			<img src="{{service_detail.images}}" alt="">
			</ul>
		</div>
	</div>
</div>

{% endblock %}

backend/shop/templates/shop/services.html
{% extends 'core/base.html' %}
{% block title %}Create a new Service | Kisan Mill {% endblock %}
{% block content %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}
  <!-- <h2>Log in to My Site</h2> -->
<style>
  .custom-row{
    display: table;
    margin:  0 auto;
    width:  550px;
  }
  h1{
    color:  #337ab7;
    text-align: center;
  }
  hr{
    height:  1px;
    background: #337ab7;
    opacity:  0.2;
  }
</style>
  <div class="container">
    <div class="row col-xs-12 col-sm-12 col-md-12">
      <div class="custom-row">
        <div class="well col-xs-12 col-md-12 col-lg-12 custom-box-shadow">
          <div class="col-sm-10 col-md-12 ">
              <h1>Create New Service</h1>
              <hr>
              <form method="post" class="form"> {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
              {% bootstrap_form form %}
                <!-- {{form.as_p}} -->
                <br>
                {% buttons %}
                    <button type="submit" name="button" class="btn btn-primary col-xs-12">
                      {% bootstrap_icon "star" %} Create Service
                    </button>
                  {% endbuttons %}
                <!-- <button type="submit" name="button" class="btn btn-primary">Create new Product</button> -->
              </form>
          </div>  
        </div>
      </div>
    </div>
  </div>
 <!--  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %} -->
  <!-- <form method="post" class="form">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" name="button" class="btn btn-primary">
          {% bootstrap_icon "star" %} Login
        </button>
      {% endbuttons %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
     <button type="submit">Log in</button>
    <a href="{% url 'core:signup' %}">New to My Site? Sign up</a>
  </form> --> 
{% endblock %}

backend/shop/templates/shop/shop.html
{% extends 'core/base.html' %}
{% block content %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- <link rel="stylesheet" type="text/css" href="https://necolas.github.io/normalize.css/7.0.0/normalize.css"> -->
<style>
	img{
		width:100%;
	}
	ul{
		list-style-type: none;
	}
	h1{
	  color:  #337ab7;
	  text-align: center;
	}
	.col-md-3{
		margin:  0 4%;
	}
	.row{
		margin:  2% 0;
	}
</style>
<ul>
<div class="list-group col-xs-12">
	<div class="container">
		<div class="row">
				<h1 class="center well custom-box-shadow">Welcome to the Kisan Mill</h1>
			  <div class="well card col-md-3 card-inverse card-success mb-3 text-center custom-box-shadow">
			  	<img src="../../../media/people-trading.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block">
			  		<div class="card-block">
			  			<li class="list-group-item"><a class="btn btn-info list-group-item list-group-item-info" href="/shop/auction/">Create an Auction</a></li>
			  		</div>
			  	</div>
			  <div class="well card col-md-3 card-inverse card-success mb-3 text-center custom-box-shadow">
			  	<img src="../../../media/shopping-list.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block rounded">
			  		<div class="card-block">
			  			<li class="list-group-item"><a class=" btn-info list-group-item list-group-item-info" href="/shop/myauction/">My Auctions and Bidding List</a></li>
			  		</div>
			  </div>
			  <div class="well card col-md-3 card-inverse card-success mb-3 text-center custom-box-shadow">
			  	<img src="../../../media/feedback.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block rounded">
			  		<div class="card-block">
			  			<li class="list-group-item"><a class=" btn-info list-group-item list-group-item-info" href="/messages/">Urgent Feedback System</a></li>
			  		</div>
			  </div>

		</div> <!-- row 1 ends-->
		<div class="row">
			<div class="well card col-md-3 card-inverse card-success mb-3 text-center custom-box-shadow">
				<img src="../../../media/notebook.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block rounded">
					<div class="card-block">
						<li class="list-group-item"><a class="btn btn-info list-group-item list-group-item-info" href="/shop/all_services/">List all the services</a></li>
					</div>
			</div>
			<div class="well card col-md-3 card-inverse card-success mb-3 text-center custom-box-shadow">
				<img src="../../../media/settings-gears.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block rounded">
					<div class="card-block">
						<li class="list-group-item"><a class="btn btn-info list-group-item list-group-item-info" href="/shop/services/">Create a new Service</a></li>
					</div>
			</div>
			<div class="well card col-md-3 card-inverse card-success mb-3 text-center custom-box-shadow">
				<img src="../../../media/molecular-bond.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block rounded">
					<div class="card-block">
						<li class="list-group-item"><a class="btn btn-info list-group-item list-group-item-info" href="/bond/">Create a new Bond</a></li>
					</div>
			</div>

		</div>
		<div class="row">
			<div class="well card col-md-3 card-inverse card-success mb-3 text-center custom-box-shadow">
				<img src="../../../media/auction.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block rounded">
					<div class="card-block">
						<li class="list-group-item"><a class=" btn-info list-group-item list-group-item-info" href="/shop/biddinglist/">List of All Auctions for Bidding</a></li>
					</div>
			</div>
			<div class="well card col-md-3 card-inverse card-success mb-3 text-center custom-box-shadow">
				<img src="../../../media/atoms.svg" class="card-img-top img-fluid img-thumbnail mx-auto d-block rounded">
					<div class="card-block">
						<li class="list-group-item"><a class="btn btn-info list-group-item list-group-item-info" href="/bond/all">List of all Bonds </a></li>
					</div>
			</div>
		</div>
	</div>
</div>
</ul>

{% endblock %}