backend/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views as core_views

app_name = 'core'

urlpatterns = [
    path('', core_views.home, name='home'),
    path('login', core_views.login_user,name='login'),

    path('log_in/', auth_views.LoginView.as_view(template_name='core/login.html'),name='login'),
    path('logout', core_views.my_logout_then_login, name='logout'),
    
    path('signup', core_views.signup, name='signup'),
]

backend/ufs/urls.py
from django.urls import path
from . import views

app_name = 'ufs'

urlpatterns =[
path('messages/',views.MessageCreateView.as_view(),name = 'ufs-messages'),
]

backend/core/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from customercorner.models import Product

class Profile(models.Model):
    id = models.AutoField(primary_key=True)
    CATEGORY_CHOICES = (('Farmer','Farmer'),('Firm','Firm'))
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    First_name = models.CharField(max_length = 15 , blank = False)
    Last_name = models.CharField(max_length = 15 , blank = False)
    bio = models.CharField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    category = models.CharField(max_length = 15 , choices = CATEGORY_CHOICES)


class MyProducts(models.Model):
    id = models.AutoField(primary_key=True)
    products_list = models.ManyToManyField(Product)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

backend/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    # birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = User
        fields = ('username','password1', 'password2', )

backend/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.views import LogoutView
from .forms import SignUpForm
from django.urls import path, resolve
from kisanmill.settings.base import LOGIN_URL


@login_required
def home(request):
    print(request.user)
    if request.user.is_authenticated():
        return render('/shop/')
    return render(request, 'core/home.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            # user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/shop/')
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {'form': form})


def login_user(request):
    if not request.user.is_anonymous:
        return redirect('/shop/')
    return redirect('/log_in/')

def logout_user(request):
    if not request.user.is_anonymous:
        return redirect('/shop/')
    return redirect('/log_in/')

class CustomLogoutView(LogoutView):
    def post(self, request, *args, **kwargs):
        logout(request)
        return redirect('/login')
    

class MyLogoutView(LogoutView):
    """make logout available via GET"""
    http_method_names = ["get", "post", "options"]

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def my_logout_then_login(request, login_url=None):
    """
    Log out the user if they are logged in. Then redirect to the login page.
    """
    # login_url = resolve(login_url or LOGIN_URL)
    return MyLogoutView.as_view(next_page='/log_in/')(request)

backend/core/templates/core/base.html
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, user-scalable=no">
    <link href='https://fonts.googleapis.com/css?family=Raleway:500,600,700,900' rel='stylesheet' type='text/css'>
    <title>{% block title %}Kisan Mill | Agriculture | Rural Development Hackathon 2018  {% endblock %}</title>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    {% bootstrap_messages %}
  </head>
  <style>
  *{
    text-decoration: none !important;
  }
  /*.well{
    background-color: #efefef !important;
  }*/
  body{
    background: url('../../media/pink dust.png')  center center fixed;
    /*background-size: cover;*/
  }
    header{
      background: #337ab7;
      position: fixed;
      width:  100%;
      z-index:  9999;
      top:  0;
      height:  100px;
      box-shadow: 0 2px 10px 2px rgba(51,122,183,0.5), 0 2px 10px 1px rgba(0, 0, 0, 0.5);
      transition:  height 100ms ease;
    }
    header.scroll_header{
      height:  70px;
    }
    main{
      position: relative;
      margin-top:  120px;
      padding-bottom:  100px;
    }
    header h1{
      text-align: center;
      color:  #f0f;
      font-weight: bold;
      font-size: 3em;
      font-family: 'Raleway';
      transition: margin-top 100ms ease;
      z-index:  999;
      position: relative;
    }
    header h1.scroll_h1{
      margin-top:  10px;
    }
    header .nav_{
      /*background: #fff;*/
      position: relative;
      /*float: right;*/
      top:  -50px;
      display: inline-block;
      padding: 0 17px;
      /*outline: 1px solid #fff;*/
      width:  100%;
      /*z-index:  -1;*/
    }
    header .nav_ *{
        padding:  10px;
        color:  #fff;
        font-family:  'Raleway';
        /*outline: 1px solid #fff;*/
        display: block;
        height:  30px;
        line-height: 10px;
        border-radius: 5px;
    }
    header .nav_ a{
      float:  right;
      z-index:  9999 !important;
      position: absolute;
      right: 20px ;
      display: inline-block;
    }
    header .nav_ p{
      float:  left;
      font-size: 1.2em;
    }
    header .nav_ #login{
      right:  90px;
    }
    header .nav_ #signup{

    }
    .custom-box-shadow{
      box-shadow: 2px 2px 2px 1px rgba(0,0,0,0.2) !important;
    }
  </style>
  <body>
    <header>
      <h1   class=""><a href="/shop" class="" style="color: #fff">Kisan Mill</a></h1>
      <div class="nav_ ">
        {% if not user.is_anonymous %}
          <p class="">Hello {{request.user}}</p>
          {% endif %}
          {% if user.is_authenticated %}
            <a href="{% url 'core:logout' %}" class="btn-danger" >logout</a>
          {% else %}
            <a href="{% url 'core:login' %}" id="login"> login</a> <a href="{% url 'core:signup' %}" id="signup">signup</a>
          {% endif %}
      </div>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>


    <script>
      window.jQuery || alert("failed to load jquery");

      $(document).ready(()=>{
        $(window).on('scroll', ()=>{
          if(!$('header').hasClass('scroll_header'))
          {
            $('header').addClass('scroll_header');
            $('header h1').addClass('scroll_h1');
          }
        });


      });


    </script>

  </body>
</html>

backend/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}

{% endblock %}

backend/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}
{% load bootstrap3 %}
  {% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}
  <!-- <h2>Log in to My Site</h2> -->
<style>
  .custom-row{
    display: table;
    margin:  0 auto;
    width:  500px;
  }

</style>
  <div class="container">
    <div class="row col-xs-12 col-sm-12 col-md-12">
      <div class="custom-row">
        <div class="well col-xs-12 col-md-12 col-lg-12 custom-box-shadow">
          <div class="col-sm-10 col-md-12 ">
              <h1 style="text-align: center">Login</h1>
              <form method="post" class="form"> {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
              {% bootstrap_form form %}
                <!-- {{form.as_p}} -->
                {% buttons %}
                    <button type="submit" name="button" class="btn btn-primary">
                      {% bootstrap_icon "star" %} Login
                    </button>
                  {% endbuttons %}
                <!-- <button type="submit" name="button" class="btn btn-primary">Create new Product</button> -->
              </form>
          </div>  
        </div>
      </div>
    </div>
  </div>
 <!--  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %} -->
  <!-- <form method="post" class="form">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" name="button" class="btn btn-primary">
          {% bootstrap_icon "star" %} Login
        </button>
      {% endbuttons %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
     <button type="submit">Log in</button>
    <a href="{% url 'core:signup' %}">New to My Site? Sign up</a>
  </form> --> 
{% endblock %}

backend/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block content %}
{% load bootstrap3 %}
  {% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}
  <!-- <h2>Log in to My Site</h2> -->
<style>
  .custom-row{
    display: table;
    margin:  0 auto;
    width:  600px;
  }

</style>
  <div class="container">
    <div class="row col-xs-12 col-sm-12 col-md-12">
      <div class="custom-row">
        <div class="well col-xs-12 col-md-12 col-lg-12 custom-box-shadow">
          <div class="col-sm-10 col-md-12 ">
              <h1 style="text-align: center">Signup</h1>
              <form method="post" class="form"> {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
              {% bootstrap_form form %}
                <!-- {{form.as_p}} -->
                {% buttons %}
                    <button type="submit" name="button" class="btn btn-primary col-xs-12">
                      {% bootstrap_icon "star" %} Signup
                    </button>
                  {% endbuttons %}
                <!-- <button type="submit" name="button" class="btn btn-primary">Create new Product</button> -->
              </form>
          </div>  
        </div>
      </div>
    </div>
  </div>
 <!--  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %} -->
  <!-- <form method="post" class="form">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" name="button" class="btn btn-primary">
          {% bootstrap_icon "star" %} Login
        </button>
      {% endbuttons %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
     <button type="submit">Log in</button>
    <a href="{% url 'core:signup' %}">New to My Site? Sign up</a>
  </form> --> 
{% endblock %}